# Generated by Django 4.1.7 on 2023-04-03 22:13

from django.db import migrations, models
import units.fields
import units.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unitsdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='Наименование юнита')),
                ('fr', models.CharField(choices=[('T', 'Terran'), ('P', 'Protoss'), ('Z', 'Zerg')], max_length=1, verbose_name='Фракция')),
                ('type', models.CharField(default='', max_length=100, verbose_name='Тип юнита')),
                ('des', models.TextField(default='', verbose_name='Описание')),
                ('img', units.fields.WEBPField(upload_to=units.models.image_folder, verbose_name='Image')),
            ],
        ),
    ]
