# Generated by Django 4.1.7 on 2023-04-25 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_unitsdb_short_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitsdb',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата публикации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitsdb',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменении'),
        ),
        migrations.AlterField(
            model_name='unitsdb',
            name='des',
            field=models.TextField(default='', null=True, verbose_name='Описание'),
        ),
    ]
