# Generated by Django 4.1.7 on 2023-04-26 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0006_unitsdb_time_create_unitsdb_time_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitsdb',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='units.customuser', verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
